version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  # backend:
  #   build:
  #     context: ./
  #     dockerfile: backend.Dockerfile
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8000:8000"
